# Generated by Django 3.2.7 on 2021-09-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/slider')),
                ('text_on_image', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('sub_text_on_image', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('description', models.TextField(default='', max_length=500)),
                ('qty', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.category')),
            ],
        ),
    ]
