# Generated by Django 3.2.7 on 2021-09-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_alter_newuser_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='username',
            field=models.CharField(blank=True, default=models.EmailField(max_length=254, unique=True), max_length=500, null=True),
        ),
    ]
