# Generated by Django 3.2.7 on 2021-09-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipping_address',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
